name: flutter_app
description: A new Flutter application.
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_screenutil: ^2.1.0
  google_fonts: ^1.1.0
flutter:
  uses-material-design: true
  assets:
    - images/

